version: '2'

services:
  konstellation_node_1_full_node:
    container_name: konstellation-node-1-full_node
    image: konstellation:darchub
    environment:
      - CHAIN_ID=darchub-1
      - MONIKER=dm-1
      - NODE_TYPE=FULL_NODE
      - KEY_NAME=satoshi
      - KEY_PASSWORD=satoshi1
      - KEY_MNEMONIC=creek round dish idea parade balance embody rate sail wheel casino suspect cute transfer pizza square cabbage valid divert gap chimney legal hurt interest
      - COIN_GENESIS=100000000darc
      - COIN_DELEGATE=100000darc
      - SEEDS=5b97506737ec2475b4b02f4c3a26476c950d14cd@192.168.10.152:26656
    ports:
    - "26666-26667:26656-26657"
    volumes:
    - ./build:/home
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  konstellation_node_2_full_node:
    container_name: konstellation-node-2-full_node
    image: konstellation:darchub
    environment:
     - CHAIN_ID=darchub-1
     - MONIKER=dm-2
     - NODE_TYPE=FULL_NODE
     - KEY_NAME=nakamoto
     - KEY_PASSWORD=nakamoto
     - KEY_MNEMONIC=bachelor miracle cook decade chalk table blouse learn vanish menu general transfer engage coast scout rookie glove affair target glide own manual consider scrub
     - COIN_GENESIS=100000000darc
     - COIN_DELEGATE=100000darc
     - SEEDS=5b97506737ec2475b4b02f4c3a26476c950d14cd@192.168.10.152:26656
    ports:
    - "26669-26670:26656-26657"
    volumes:
    - ./build:/home
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  konstellation_node_3_full_node:
    container_name: konstellation-node-3-full_node
    image: konstellation:darchub
    environment:
      - CHAIN_ID=darchub-1
      - MONIKER=dm-3
      - NODE_TYPE=FULL_NODE
      - KEY_NAME=vitalik
      - KEY_PASSWORD=vitalik1
      - KEY_MNEMONIC=hair reunion riot fish hawk arch buzz debris arch easily search glove private rival boat resist chaos cause panda icon pave shock egg ability
      - COIN_GENESIS=100000000darc
      - COIN_DELEGATE=100000darc
      - SEEDS=5b97506737ec2475b4b02f4c3a26476c950d14cd@192.168.10.152:26656
    ports:
    - "26671-26672:26656-26657"
    volumes:
    - ./build:/home
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  konstellation_node_4_full_node:
    container_name: konstellation-node-4-full_node
    image: konstellation:darchub
    environment:
      - CHAIN_ID=darchub-1
      - MONIKER=dm-4
      - NODE_TYPE=FULL_NODE
      - KEY_NAME=buterin
      - KEY_PASSWORD=buterin1
      - KEY_MNEMONIC=other original trouble craft hard loan ostrich aim drastic team absent kiwi matrix dose engage cup novel humor brave budget stage label future exile
      - COIN_GENESIS=100000000darc
      - COIN_DELEGATE=100000darc
      - SEEDS=5b97506737ec2475b4b02f4c3a26476c950d14cd@192.168.10.152:26656
    ports:
    - "26673-26674:26656-26657"
    volumes:
    - ./build:/home
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  konstellation_node_5_seed:
    container_name: konstellation-node-5-seed
    image: konstellation:darchub
    environment:
      - CHAIN_ID=darchub-1
      - MONIKER=dm-5
      - NODE_TYPE=FULL_NODE
      - SEED=true
      - SEEDS=5b97506737ec2475b4b02f4c3a26476c950d14cd@192.168.10.152:26656
    ports:
    - "26675-26676:26656-26657"
    volumes:
    - ./build:/home
    networks:
      localnet:
        ipv4_address: 192.168.10.6

networks:
  localnet:
    driver: bridge
##    // for docker network create -d bridge --subnet 192.168.10.0/8 --gateway 192.168.10.1 konstellation_localnet
#    external: true
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/24
        gateway: 192.168.10.1