# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &build_defaults
  working_directory: /go/src/github.com/konstellation/konstellation
  docker:
    - image: circleci/golang:1.13
  environment:
    GOBIN: /tmp/workspace/bin

deps: &dependencies
  run:
    name: dependencies
    command: |
      export PATH="$GOBIN:$PATH"

jobs:
  build:
    <<: *build_defaults
    steps:
      - checkout
      - run:
          name: run build konstellation
          command: |
            go build -v ./client/konstellation
            go build -v ./client/konstellationcli
            go build -v ./client/konstellationlcd
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...

#  build:
#    steps:
#      - run: mkdir -p /tmp/workspace/bin
#      - run: mkdir -p /tmp/workspace/profiles
#      - checkout
#      - restore_cache:
#          keys:
#            - go-mod-v1-{{ checksum "go.sum" }}
#      - run:
#          name: tools
#          command: |
#            export PATH="$GOBIN:$PATH"
#            make tools
#      - *dependencies
#      - run:
#          name: binaries
#          command: |
#            export PATH="$GOBIN:$PATH"
#            make install
#      - save_cache:
#          key: go-mod-v1-{{ checksum "go.sum" }}
#          paths:
#            - "/go/pkg/mod"
#      - persist_to_workspace:
#          root: /tmp/workspace
#          paths:
#            - bin
#            - profiles
#      - store_artifacts:
#          path: /tmp/workspace/bin/konstellation
#          destination: linux/konstellation
#      - store_artifacts:
#          path: /tmp/workspace/bin/konstellationcli
#          destination: linux/konstellationcli
#      - store_artifacts:
#          path: /tmp/workspace/bin/konstellationlcd
#          destination: linux/konstellationlcd

workflows:
  version: 2
  build-konstellation:
    jobs:
      - build:
          # filters here are needed to enable this job also for tags
          filters:
            tags:
              only:
                - /^v.*/