# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &linux_defaults
  working_directory: /go/src/github.com/konstellation/konstellation
  docker:
    - image: circleci/golang:1.13
  environment:
    GOBIN: /tmp/workspace/bin

deps: &dependencies
  run:
    name: dependencies
    command: |
      export PATH="$GOBIN:$PATH"

jobs:
  build:
    <<: *linux_defaults
    steps:
      - run: mkdir -p /tmp/workspace/bin
      - run: mkdir -p /tmp/workspace/profiles
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: tools
          command: |
            export PATH="$GOBIN:$PATH"
            make tools
      - *dependencies
      - run:
          name: binaries
          command: |
            export PATH="$GOBIN:$PATH"
            make install
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - bin
            - profiles
      - store_artifacts:
          path: /tmp/workspace/bin/konstellation
          destination: konstellation
      - store_artifacts:
          path: /tmp/workspace/bin/konstellationcli
          destination: konstellationcli
      - store_artifacts:
          path: /tmp/workspace/bin/konstellationlcd
          destination: konstellationlcd
      - store_artifacts:
          path: /tmp/bin

workflows:
  version: 2
  test-suite:
    jobs:
      - build:
          # filters here are needed to enable this job also for tags
          filters:
            tags:
              only:
                - /^v.*/